### ISSUE TITLE
[Epic] Improve automation for provider upgrades

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/upgrade-provider#143]
**Objective**: Drive provider update+release overhead to <4 hrs per week.
**Estimated cost**: 4 eng-weeks
**Impact**: regain ~3 eng-days per week

Analysis:
We do a lot of provider upgrades (~29/week! [Metabase](https://metabase.corp.pulumi.com/question/2660-provider-update-prs-this-quarter)). All upgrades require a three step process to merge and release which consumes ~30min of eng time (mostly due to switching costs from long latency between steps) Automating the release step after merging a version bump should save about 2 eng days per week. 

About 30% of upgrades required a manual PR ([Metabase](https://metabase.corp.pulumi.com/question/2661-manual-provider-update-prs-this-quarter)). About 1/3 of those are difficult to automate (upstream breaking changes), but up to 2/3s are caused by small breakages in our upgrade-provider tool. We spend about 1.5hr per manual PR. Eliminating this latter category of breakages requireing manual PRs would save roughly an additional 1 eng-day per week.

Detailed Scope of Work:
- [ ] https://github.com/pulumi/home/issues/3071 (1 eng week)
  - [ ] https://github.com/pulumi/release-bot/issues/62
  - [ ] https://github.com/pulumi/action-release-by-pr-label/issues/3
- [x] #147
- [ ] [Add basic integration testing for upgrade-provider](https://github.com/pulumi/upgrade-provider/issues/31) (1 eng week)
- [ ] #146
- [ ] #145
- [ ] Audit and Fix misc failures (timeboxed to 3 eng days)
  - [x] #144
  - [ ] https://github.com/pulumi/upgrade-provider/issues/104
  - [x] https://github.com/pulumi/upgrade-provider/issues/80
  - [ ] https://github.com/pulumi/upgrade-provider/issues/168
  - [ ] ...

**Comment by iwahbe** [comment]
Recent analysis has shown that > 95% of provider upgrades are automatic. Observationally, provider upgrades take ~2 hours per week. While there is plenty of improvement to make in our existing provider automation, the current system works and works well.
