### ISSUE TITLE
Enable `Check upstream upgrade` workflow

### ISSUE THREAD

**Issue by iwahbe** [pulumi/upgrade-provider#225]
This issue consolidates workflow failures that need to be addressed:

```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/pulumi-f5bigip/issues/345
- [ ] https://github.com/pulumi/pulumi-wavefront/issues/287	
- [ ] https://github.com/pulumi/pulumi-cloudinit/issues/187
- [ ] https://github.com/pulumi/pulumi-dnsimple/issues/267
- [ ] https://github.com/pulumi/pulumi-mysql/issues/286
- [ ] https://github.com/pulumi/pulumi-venafi/issues/244
- [ ] https://github.com/pulumi/pulumi-http/issues/70
- [ ] https://github.com/pulumi/pulumi-null/issues/72
```

**Comment by iwahbe** [comment]
I am labeling this a P1, since it prevents us from knowing if we are meeting our upgrade SLO.

**Comment by guineveresaenger** [comment]
These P1s are all resolved.

Common themes:

- An upstream tag was not mapped to the pinned commit in go.mod
- An upstream repository was not detected
- Upstream had migrated to a new org
