### ISSUE TITLE
Refactor `upgrade-provider` to work for any provider

### ISSUE THREAD

**Issue by aq17** [pulumi/upgrade-provider#67]
Right now, `upgrade-provider` implicitly assumes we are updating a pulumi-maintained provider within our pulumi github organization. 

```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/upgrade-provider/issues/65
- [x] https://github.com/pulumi/upgrade-provider/issues/55
- [x] https://github.com/pulumi/upgrade-provider/issues/52
- [ ] https://github.com/pulumi/upgrade-provider/issues/53
- [x] https://github.com/pulumi/upgrade-provider/issues/69
- [ ] https://github.com/pulumi/upgrade-provider/issues/70
```
